name: Nightly Build - Android

on:
  schedule:
  - cron: "45 23 * * *"    
  repository_dispatch:
   types: androidnightly
  
jobs:  
  build:
    name: "Nightly Build - Android"
    env:
        ANDROID_HOME: "/Users/runner/Library/Android/sdk"
        ScreenshotFolder: "/Users/runner/screenshots"
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2.3.4
            
    - uses: malinskiy/action-android/install-sdk@release/0.1.1
    - run: sdkmanager "platform-tools" "platforms;android-29"
    - run: sdkmanager "build-tools;30.0.2"
    - run: adb devices

    - name: Set Up Variables
      run: echo "action_url=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV

    - name: Set up Appium
      run: |
        npm install -g appium --unsafe-perm=true --allow-root
        
    - name: Setup Nuget
      uses: olegtarasov/download-nuget@v1
      
    - name: Setup Nuget
      uses: olegtarasov/download-nuget@v1
          
    - name: Restore Nuget Packages
      run: mono $NUGET_EXE restore VoucherRedemptionMobile.sln -source "https://api.nuget.org/v3/index.json;https://www.myget.org/F/transactionprocessing/api/v3/index.json"

    - name: Build Code
      run: msbuild /p:Configuration="Release" /p:Platform="iPhoneSimulator" /t:Build VoucherRedemptionMobile.sln

    - name: Build APK
      run: msbuild VoucherRedemptionMobile.Android/VoucherRedemptionMobile.Android.csproj -target:SignAndroidPackage /p:Configuration=Release  

    - name: Create Screenshot Folder
      run: mkdir -p /Users/runner/screenshots
      
    - name: Run Integration Tests - Android
      uses: malinskiy/action-android/emulator-run-cmd@release/0.1.1
      with:
          cmd: dotnet test VoucherRedemptionMobile.IntegrationTests.WithAppium/VoucherRedemptionMobile.IntegrationTests.WithAppium.csproj --filter (Category=Android)
          api: 28
          tag: default
          abi: x86   
          verbose: false

    - uses: actions/upload-artifact@v2.2.1
      if: failure()
      with:
        name: screenshots
        path: /Users/runner/screenshots/**/*

    - uses: nashmaniac/create-issue-action@v1.1
      if: ${{ failure() }}
      name: Create an issue on build failure
      with:
        title: Investigate Nightly Build Failure
        token: ${{secrets.GITHUB_TOKEN}}
        labels: nightlybuild
        body: Url is ${{env.action_url}}
